name: et-fundacion

channels:
  - conda-forge

dependencies:
  - python=3.12
  - earthengine-api=1.7.38
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - rasterio
  - scipy
  - shapely
  - ipykernel
  - pytest
  - pip
